### ISSUE TITLE
Provide option for using tsconfig.json file

### ISSUE THREAD

**Issue by nicky-lenaers** [rogierschouten/gulp-typedoc#10]
I'd like to see an option for including the config settings from the ``tsconfig.json`` file that is present in many TypeScript projects. This would keep settings in sync and minimize discrepancy.

Thanks!

**Comment by rogierschouten** [comment]
Is that a gulp-typedoc request or a typedoc request? Any option used by typedoc would be transparently available in gulp-typedoc.

**Comment by Stargateur** [comment]
It would be great if you provide a way to do like gulp-typescript with tsconfig.json

`gulp.task("compile:ts", function() {
  let tsProject = ts.createProject("tsconfig.json");
  let tsResult = tsProject.src().pipe(ts(tsProject));
  return tsResult.js.pipe(gulp.dest("dist/js"));
});`

I do this it's work but it's a little ugly :hankey: 
`gulp.task("doc", function() {
  let tsProject = ts.createProject("tsconfig.json");
  return tsProject.src()
    .pipe(typedoc({
      out: "dist/doc",
      tsconfig: "tsconfig.json",
      name: "seeart",
    }));
});`

In a same way we can't pipe the output with gulp.dest.
