### ISSUE TITLE
Exclude option not working 

### ISSUE THREAD

**Issue by Louis-Philippe-Monette** [rogierschouten/gulp-typedoc#11]
I trying to exclude some files for the gulp-typedoc tool and they are processed anyway. 
Here is my gulp file:

var gulp = require('gulp');
var typedoc = require("gulp-typedoc");

gulp.task("doc", function() 
{
  return gulp.src(["app/**/*.ts"])
    .pipe(typedoc({ 

      // TypeScript options (see typescript docs) 
      module: "commonjs", 
      target: "es6",
      experimentalDecorators: true,

      // Output options (see typedoc docs) 
      out: "./Doc", 

      // TypeDoc options (see typedoc docs) 

      exclude: "**/*.spec.ts",
      // since the exclude tag is not working, I have put ignoreCompilerErrors to true to create the doc anyway.
      // ignoreCompilerErrors: true,

      name: "One MiniStar", 
      version: true

      })) ;
});

**Comment by rogierschouten** [comment]
Hi @Louis-Philippe-Monette,   gulp-typedoc passes the options object directly to typedoc without processing it, so there is nothing I can do about it.  It may be that the exclude option does not work if typedoc is used in API mode, only in CLI mode.  In any case, you can use e.g. gulp-ignore to exclude files in Gulp.  If you do feel this is something in gulp-typedoc, please feel free to re-open.

**Comment by pcssi** [comment]
@Louis-Philippe-Monette or @rogierschouten were you able to determine if the exclude option works in typedoc in API mode as well as in CLI mode?
