### ISSUE TITLE
Change the typedoc dependencies to peer

### ISSUE THREAD

**Issue by mizunashi-mana** [rogierschouten/gulp-typedoc#13]
like [gulp-tslint](https://github.com/panuhorsmalahti/gulp-tslint/blob/master/package.json#L43) or add option we can use custom typedoc like [gulp-typescript](https://github.com/ivogabe/gulp-typescript).

As you know, typedoc is updating to use typescript 1.8.10 by https://github.com/TypeStrong/typedoc/pull/204.
Now, we should use [sierrasoftworks/typedoc#v1.8.10](https://github.com/sierrasoftworks/typedoc) if we use typescript latest, and we should use [sierrasoftworks/gulp-typedoc#v1.8.10](https://github.com/sierrasoftworks/gulp-typedoc).

However, I want to use original repo as possible, and there are some situations to use own custom typedoc with this plugin.

What about this suggestion?

**Comment by rogierschouten** [comment]
Good idea, I'll look into it next week. Or you could send me a PR of
course,  I'd appreciate it.

**Comment by mizunashi-mana** [comment]
Thank you for merge!

**Comment by rogierschouten** [comment]
Published on NPM v2.0.0
