### ISSUE TITLE
Problems getting started - no output generated

### ISSUE THREAD

**Issue by parky128** [rogierschouten/gulp-typedoc#17]
Hi,

I am trying to get this plugin to work for my angular typescript project and have defined a gulp task like so:

```javascript
gulp.task('typedoc', function() {
  return gulp
    .src(['./src/client/typings/**/*.d.ts',
        './src/client/app/**/*.module.ts',
        './src/client/app/**/*.run.ts',
        './src/client/app/**/*.config.ts',
        './src/client/app/**/*.enum.ts',
        './src/client/app/**/*.controller.ts',
        './src/client/app/**/*.model.ts',
        './src/client/app/**/*.directive.ts',
        './src/client/app/**/*.filter.ts',
        './src/client/app/**/*.service.ts',
        './src/client/app/interfaces/**/*.ts'])
    .pipe(plugins.typedoc({
      module: 'commonjs',
      target: 'es5',
      includeDeclarations: true,
      out: 'docs/',
      name: 'My project title',
      ignoreCompilerErrors: false,
      version: true
    }));
});
```

When I run the task I just get the following in the console:

```
[12:22:18] Starting 'typedoc'...
[12:22:20]
TypeDoc {{ VERSION }}
Using TypeScript 2.1.6 from C:\Users\rparker\Documents\GitHub\interact\node_modules\typedoc\node_modules\typescript\lib
```

Nothing gets output into my docs directory, and the task never completes.

I notice in the docs it says

> The plugin takes an object, of which all properties are passed transparently to typedoc. Pipe in TypeScript files. The documentation files are not piped out.

Last sentence says the files are not piped out, is that correct? If so, how do I get the files for viewing?

Thanks

**Comment by parky128** [comment]
Ok, so I have managed to get files generated but only by reducing the number of source files being piped. 
So I changed my gulp src paths to:

```
.src(['./src/client/typings/**/*.ts',
      './src/client/app/interfaces/**/*.ts',
      './src/client/app/**/*.module.ts',
      './src/client/app/**/*.service.ts'
      ])
```

And after 7 mins the gulp task started rendering the doc files.

Why does it take so long to process these files? Is there anyway to speed this up through config options?

I also see that every file gets listed in the generated docs as a global, not sure that's correct?

**Comment by rogierschouten** [comment]
Hi @parky128    As you saw, files are not piped back into the gulp system but rather just saved on disk. 

The gulp plugin is just a passthrough to the actual typedoc program, which I don't own - so you'd have to report the slowness there. What you can still try, is to execute typedoc using gulp-exec instead. That way, you avoid piping in the source files through the gulp system. Maybe that helps.

**Comment by rogierschouten** [comment]
By the way please feel free to re-open this issue if you need further help
