### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by kennethjevans** [rogierschouten/gulp-typedoc#19]
Could you please have this plugin not execute if no files are passed to it?  Right now it throws an error.  It might sound like an odd request, but a lot of people use the gulp-newer plugin that passes all files through if and only if any of them have a modification time newer than the destination file.

This saves tons of time when you have your build broken down into a bunch of small tasks.  Because each task only executes if its source files are newer than its output file.  I would like to use it so the documentation is only rebuilt if any of the source files are newer than the documentation index.html file.

return gulp.src(SOURCE_FILES)
   .pipe(newer(DOC_DIR + "index.html")
   .pipe(typedoc(...));

It seems to be common practice to have this behavior as I'm using a 9 other gulp plugins and they don't perform any actions or throw any errors if they aren't feed any files.

Also, thanks for your hard work on the plugin.  It is a great help.

**Comment by rogierschouten** [comment]
Thank you for reporting this, I agree.  I changed it and released it as v2.0.3

**Comment by kennethjevans** [comment]
Thank you.  It works great.
