### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by TvrtkoM** [rogierschouten/gulp-typedoc#29]
It would be cool if README has more content, examples etc.

For example there is no typescript option "includeDeclarations", I think there was no such thing in typescript (tsc or tsconfig) at all.

**Comment by rogierschouten** [comment]
No it's an option of typedoc not typescript. You may want to refer to the typedoc documentation instead.  This is simply a gulp wrapper with a passthrough to typedoc. 

I don't use this myself anymore, but if you have a suggestion for better docs, I'll happily merge PRs
