### ISSUE TITLE
Typedoc added an 'excludeNotExported' option in the most recent release

### ISSUE THREAD

**Issue by sccolbert** [rogierschouten/gulp-typedoc#3]
It would be nice to allow this as an option:
https://github.com/sebastian-lenz/typedoc/commit/c288c9bdb402140ceda25faf1d32f3a09a87a2c7

**Comment by sccolbert** [comment]
Noise. This was nothing but noise. Apologies.

**Comment by rogierschouten** [comment]
No problem mate, thanks for contributing!
