### ISSUE TITLE
Error in plugin "gulp-typedoc" 

### ISSUE THREAD

**Issue by callmeioy** [rogierschouten/gulp-typedoc#38]
hello,i use typedoc and gulp-typedoc order to get markdown file
when i run  gulp without install npm plugin 'typedoc-plugin-markdown'
anythings is all right.
but when i run gulp with install npm plugin 'typedoc-plugin-markdown',
it was some error  has happen
`npm run gulpdoc`
![image](https://user-images.githubusercontent.com/14991009/119964785-25092a00-bfdc-11eb-936e-013e2ab5b7df.png)

my gulpfile.js

![image](https://user-images.githubusercontent.com/14991009/119966048-7ebe2400-bfdd-11eb-962c-297bc333b9ec.png)

my package.json
![image](https://user-images.githubusercontent.com/14991009/119966140-95fd1180-bfdd-11eb-81f3-36582c27fa08.png)

if i just run typedoc ,it was all right too

`npm run typedoc`

result like this ,it generate some  *.md  file

![image](https://user-images.githubusercontent.com/14991009/119965544-f6d81a00-bfdc-11eb-8151-6c165f3114bc.png)

what   shoud   i  to do,hope to get some help ,thanks

**Comment by rogierschouten** [comment]
Hi @callmeioy , I think you should use 'plugin' instead of 'plugins'  as option on line 8 of your gulp file. 

Hope this helps.
