### ISSUE TITLE
Should there be entryPoints according to typedoc?

### ISSUE THREAD

**Issue by rprashanth-lenovo** [rogierschouten/gulp-typedoc#40]
According to the typedoc 0.20.36 version, I think the app.bootstrap() should have an entryPoints option like below

app.bootstrap({
// typedoc options here
entryPoints: ["src/index.ts"],
});

Currently with the latest gulp-typedoc version and with the below code
this.gulp.src(["./source/**/*.ts"])
                    .pipe(typedoc({out: "typedoc/",
                    hideGenerator: true,
                    name: "test"}));

The output is not generated as expected. It just renders with empty HTML.
![image](https://user-images.githubusercontent.com/56639996/120631198-3becc800-c485-11eb-9112-c26c54cba874.png)

**Comment by rogierschouten** [comment]
Would you be willing to submit a PR?  I have not used this package for years myself and I have less and less time to maintain it for others tbh. Please let me know and I will do my best with a quick merge.

**Comment by rprashanth-lenovo** [comment]
Sure. I can push the changes. Can you give permissions for me to create pull requests? Currently, it shows 
`remote: Permission to rogierschouten/gulp-typedoc.git denied to robinprashanth.
fatal: unable to access 'https://github.com/rogierschouten/gulp-typedoc.git/': The requested URL returned error: 403`

**Comment by rogierschouten** [comment]
Are you sure you are doing it right?  I have no settings that limit making PRs.  Can you click the green 'New PR'  button here: https://github.com/rogierschouten/gulp-typedoc/pulls  ?

**Comment by rogierschouten** [comment]
You are forking the repo and then making a PR, right?

**Comment by robinprashanth** [comment]
@rogierschouten Sorry I was having issues on my machine. Now I have created PR for the same https://github.com/rogierschouten/gulp-typedoc/pull/41/files. Review when you get time.

**Comment by rogierschouten** [comment]
Solution published as v3.0.1.  Thank you!
