### ISSUE TITLE
gulp-typedoc options overwritten

### ISSUE THREAD

**Issue by tristan00b** [rogierschouten/gulp-typedoc#44]
Hello, 
I'm sending an object reference to the gulp-typedoc constructor like so:

```js
import typedoc from 'gulp-typedoc'

const options = {
  typedoc: {
    name: projectName,
    out: paths.dest.docs,
    theme: 'default',
    version: true,
  }
}

const docs = async () => {
  return src(`${paths.src.root}/engine/**/*.ts`)
    .pipe(typedoc(options.typedoc))
    .on('error', log.error)
}
```

This works fine on the first run, but fails on subsequent runs due to mutations to `options.typedoc`, which changes to this:

```'
{
  name: projectName,
  theme: 'default',
  logger: [Function (anonymous)]
}
```

As a result, I get the following error message:

```
[PluginError: You must either specify the 'out' or 'json' option.] {
  plugin: 'gulp-typedoc',
  showProperties: true,
  showStack: false,
  __safety: { toString: [Function: bound ] }
}
```

**Comment by tristan00b** [comment]
I was just looking at your `index.js` and saw the [comment](https://github.com/rogierschouten/gulp-typedoc/blob/01603b24e7ffb26048289f8797b94d974526555a/index.js#L33) about `options.out` and `options.version` causing problems with typedoc.

I looks like all of `gulp-typedocs` options are safe to use with `JSON.stringify` in order to make a clean copy though? I'd be happy to submit a PR.

**Comment by tristan00b** [comment]
I have just tried removing the lines deleting the `out`, `json`, and `version` properties from `options` and this doesn't seem to cause any problems with the latest versions of Typedoc and Typescript&mdash;at least when running your tests.

But I think making a clean copy of `options` to work with is still a good idea.

**Comment by rogierschouten** [comment]
Great job submitting a PR @tristan00b !   I totally agree with you.   let's close this issue and continue our discussion in the PR, ok?
