### ISSUE TITLE
Is there a way to generate docs in presence of TypeScript errors?

### ISSUE THREAD

**Issue by 3nsoft** [rogierschouten/gulp-typedoc#5]
Is there a way to generate docs in presence of TypeScript errors?
Sometimes, even often, it is needed to make docs for your team, even when code has a few compile-time glitches.
Thank you for this work. Awesome and useful lib.

**Comment by rogierschouten** [comment]
Thanks mate! You'd have to ask at TypeDoc, not at gulp-typedoc...

**Comment by 3nsoft** [comment]
TypeDoc guys have a say in https://github.com/sebastian-lenz/typedoc/issues/116

TLDR; Version 0.3.6 (of TypeDoc) is now on NPM which allows you to specify the --ignoreCompilerErrors argument.

How can this flag be set in gulp-typedoc?

**Comment by rogierschouten** [comment]
Gulp-typedoc transparently passes all options on to typedoc. Simply specify ignoreCompilerErrors like so:

```javascript
var typedoc = require("gulp-typedoc");

gulp.task("typedoc", function() {
    return gulp
        .src(["data/*.ts"])
        .pipe(typedoc({ 
            ignoreCompilerErrors: true
        }))
    ;
});
```
I hope this helps you out. If it doesn't work, let me know.
