### ISSUE TITLE
Gulp plugin, command line too long

### ISSUE THREAD

**Issue by robertbaker** [rogierschouten/gulp-typedoc#6]
Is it possible to provide an option in the plugin to have it use a folder. spawning a child process is less than ideal.

Support the theme config option too.

Grunt plugin does this, should be possible too.

**Comment by rogierschouten** [comment]
Hi @robertbaker,
Good idea not to spawn a child process. This wasn't possible earlier but it seems it is now indeed. 

The theme config option is already supported, as gulp-typedoc transparently passes all options to TypeDoc, simply use 
```javascript
gulp.task("typedoc", function() {
    return gulp
        .src(["data/*.ts"])
        .pipe(typedoc({ 
            theme: "/path/to/theme"
        }))
    ;
});
```

And what do you mean by using a folder? Output folder is supported. Input folder can be done using 
```javascript
gulp.src("myfolder/**/*.ts)
```

Also, in the future, please submit separate issues for separate, ehm, issues. Thanks.

**Comment by rogierschouten** [comment]
Child process no longer started by commit d9ee7872c110b28a60f362fd4c4e56e14a75e218

**Comment by robertbaker** [comment]
I mean for the command line to long issue. Use a folder instead of listing
all files.

**Comment by rogierschouten** [comment]
Ah ok. Well that's fixed now so I guess we're good then.
