### ISSUE TITLE
JSON options not recognized 

### ISSUE THREAD

**Issue by FlippieCoetser** [rogierschouten/gulp-typedoc#7]
Receive ```Unkown option: json``` When trying to configuring ```json: "path" ``` in ```gulpfile.js```

**Comment by rogierschouten** [comment]
Ah thanks for reporting. That means that typedoc has been updated with a new error check. I'll fix this.

**Comment by rogierschouten** [comment]
fixed in version 1.2.1 commit 4fa37de3a7254eea89751baea0b24fe5556ad627
