### ISSUE TITLE
Specify the version of typedoc

### ISSUE THREAD

**Issue by kpau** [rogierschouten/gulp-typedoc#9]
Currently in our project we are using TypeScript 1.5.3. The latest version is 1.6.0-beta.
typedoc v0.8 is using TS 1.5.3, and typedoc v0.9 and newer is using TS 1.6.0-beta.

Is it possible to specify which version of typedoc (or TypeScript) to use?
Can you add such config?

Thanks!
Kristiyan

**Comment by majo44** [comment]
+1

**Comment by rogierschouten** [comment]
You need to ask this question of typedoc, not gulp-typedoc. This is just a frontend.
